In [44]:
## Import dependencies
import pandas as pd
import scipy.stats as stats
import numpy as np

## Importing data
filepath = "COVID-19_Aggregate_Cases_Current_Daily_County_Health.csv"
outputPath = "Covid-19_Monthly_Data"

In [3]:
## Reading in our file to a dataframe
covidDF = pd.read_csv(filepath)

In [4]:
## Sorting by county and date
covidCounty = covidDF.sort_values(["Jurisdiction", "Date"])
covidCounty.head()

,Jurisdiction,Date,New Cases,7-day Average New Cases,Cumulative cases,Population (2019),New Case Rate,7-Day Average New Case Rate,Cumulative Case Rate,County FIPS Code,Longitude,Latitude,Georeferenced Lat & Long
21211,Adams,01/01/2021,52,79.0,4761,103009,50.5,76.7,4621.9,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565)
15411,Adams,01/02/2021,67,78.3,4828,103009,65.0,76.0,4687.0,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565)
15903,Adams,01/03/2021,21,75.7,4849,103009,20.4,73.5,4707.4,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565)
18531,Adams,01/04/2021,85,75.7,4934,103009,82.5,73.5,4789.9,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565)
24447,Adams,01/05/2021,126,74.1,5060,103009,122.3,72.0,4912.2,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565)

In [5]:
## Converting date to datatime type in order to convert to monthly data
covidCounty["Date"] = pd.to_datetime(covidCounty["Date"])
covidCounty.head()

,Jurisdiction,Date,New Cases,7-day Average New Cases,Cumulative cases,Population (2019),New Case Rate,7-Day Average New Case Rate,Cumulative Case Rate,County FIPS Code,Longitude,Latitude,Georeferenced Lat & Long
21211,Adams,2021-01-01,52,79.0,4761,103009,50.5,76.7,4621.9,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565)
15411,Adams,2021-01-02,67,78.3,4828,103009,65.0,76.0,4687.0,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565)
15903,Adams,2021-01-03,21,75.7,4849,103009,20.4,73.5,4707.4,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565)
18531,Adams,2021-01-04,85,75.7,4934,103009,82.5,73.5,4789.9,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565)
24447,Adams,2021-01-05,126,74.1,5060,103009,122.3,72.0,4912.2,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565)

In [6]:
covidCounty["Month"] = covidCounty["Date"].dt.to_period("M")

In [7]:
covidCounty.head()

,Jurisdiction,Date,New Cases,7-day Average New Cases,Cumulative cases,Population (2019),New Case Rate,7-Day Average New Case Rate,Cumulative Case Rate,County FIPS Code,Longitude,Latitude,Georeferenced Lat & Long,Month
21211,Adams,2021-01-01,52,79.0,4761,103009,50.5,76.7,4621.9,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565),2021-01
15411,Adams,2021-01-02,67,78.3,4828,103009,65.0,76.0,4687.0,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565),2021-01
15903,Adams,2021-01-03,21,75.7,4849,103009,20.4,73.5,4707.4,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565),2021-01
18531,Adams,2021-01-04,85,75.7,4934,103009,82.5,73.5,4789.9,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565),2021-01
24447,Adams,2021-01-05,126,74.1,5060,103009,122.3,72.0,4912.2,42001,-77.222243,39.872096,POINT (-77.22224271 39.87209565),2021-01

In [27]:
groupDF = covidCounty.groupby(["Jurisdiction", "Month"])

In [40]:
groupedSUM = groupDF.sum()
groupedSUM.reset_index(inplace = True)
regularGroup = groupDF.head(1000000000)
groupedSUM

,Jurisdiction,Month,New Cases,7-day Average New Cases,Cumulative cases,Population (2019),New Case Rate,7-Day Average New Case Rate,Cumulative Case Rate,County FIPS Code,Longitude,Latitude
0,Adams,2020-03,13,9.5,98,3193279,12.8,9.1,95.1,1302031,-2393.889524,1236.034965
1,Adams,2020-04,130,120.8,2270,3090270,126.6,117.3,2203.9,1260030,-2316.667281,1196.162869
2,Adams,2020-05,113,118.1,6134,3193279,109.7,114.7,5954.6,1302031,-2393.889524,1236.034965
3,Adams,2020-06,93,90.2,9194,3090270,90.3,87.6,8925.3,1260030,-2316.667281,1196.162869
4,Adams,2020-07,132,127.0,12852,3193279,128.0,123.4,12476.5,1302031,-2393.889524,1236.034965
...,...,...,...,...,...,...,...,...,...,...,...,...
1151,York,2021-03,3823,3613.8,1169122,13920798,851.3,804.6,260350.0,1306123,-2378.498576,1237.579685
1152,York,2021-04,4675,4708.9,1268529,13471740,1041.2,1048.7,282486.5,1263990,-2301.772816,1197.657759
1153,York,2021-05,2123,2470.0,1419960,13920798,472.7,549.9,316208.7,1306123,-2378.498576,1237.579685
1154,York,2021-06,429,492.3,1406384,13471740,95.2,109.6,313185.4,1263990,-2301.772816,1197.657759
1155,York,2021-07,413,344.7,1321341,12573624,91.8,76.7,294247.4,1179724,-2148.321295,1117.813909

In [43]:
summedDF = pd.DataFrame({"County" : groupedSUM["Jurisdiction"],
                        "Date" : groupedSUM["Month"],
                        "Monthly Cases" : groupedSUM["New Cases"],
                        "Longitude" : regularGroup["Longitude"],
                        "Latitude" : regularGroup["Latitude"]}).dropna()
summedDF

     County     Date  Monthly Cases  Longitude   Latitude
0     Adams  2020-03           13.0 -79.762866  41.403413
1     Adams  2020-04          130.0 -76.223324  40.707512
2     Adams  2020-05          113.0 -76.779606  40.419746
3     Adams  2020-06           93.0 -76.779606  40.419746
4     Adams  2020-07          132.0 -76.779606  40.419746
...     ...      ...            ...        ...        ...
1151   York  2021-03         3823.0 -79.762866  41.403413
1152   York  2021-04         4675.0 -78.491165  40.007375
1153   York  2021-05         2123.0 -79.762866  41.403413
1154   York  2021-06          429.0 -75.340836  41.060918
1155   York  2021-07          413.0 -79.762866  41.403413

[1156 rows x 5 columns]

In [45]:
summedDF.to_csv(outputPath)